# Generated by Django 2.1.2 on 2019-03-13 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('payment_customer_id', models.CharField(max_length=11)),
                ('payment_date', models.DateTimeField(default=datetime.datetime(2019, 3, 13, 17, 55, 13, 894115, tzinfo=utc))),
                ('payment_bill', models.CharField(max_length=50)),
                ('payment_type', models.CharField(max_length=8)),
                ('payment_description', models.TextField(max_length=200)),
            ],
        ),
    ]
