# Generated by Django 2.1.7 on 2019-07-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_vehicle_name', models.CharField(max_length=20)),
                ('customer_addres', models.TextField(max_length=200)),
                ('customer_emi', models.CharField(max_length=10)),
                ('customer_emi_palan', models.CharField(max_length=10)),
                ('customer_done_payment', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.CharField(max_length=10),
        ),
    ]
