# Generated by Django 2.2 on 2019-05-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('bike_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('bike_customer', models.CharField(max_length=50)),
                ('bike_number', models.CharField(max_length=15)),
                ('bike_type', models.CharField(max_length=50)),
                ('bike_company', models.CharField(max_length=50)),
                ('bike_description', models.CharField(max_length=500)),
            ],
        ),
    ]
