# Generated by Django 2.2 on 2019-05-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('insurance_bike_id', models.CharField(max_length=15)),
                ('insurance_number', models.CharField(max_length=15)),
                ('insurance_date', models.CharField(max_length=10)),
                ('insurance_expiry', models.CharField(max_length=10)),
                ('insurance_amount', models.CharField(max_length=8)),
                ('insurance_type', models.CharField(max_length=20)),
                ('insurance_description', models.CharField(max_length=500)),
            ],
        ),
    ]
