# Generated by Django 2.1.7 on 2019-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('customer_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('joinng_date', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
    ]
