# Generated by Django 2.2 on 2019-05-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_mobile', models.CharField(max_length=10)),
                ('customer_email', models.CharField(max_length=150)),
                ('customer_username', models.CharField(max_length=50)),
                ('customer_password', models.CharField(max_length=256)),
                ('customer_address', models.CharField(max_length=500)),
            ],
        ),
    ]
